services:
  database:
    image: 'postgres:16.0'
    container_name: 'test-db'
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: root
    ports:
      - "15432:5432"
  app:
    build: .
    restart: always
    container_name: 'test-app'
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DB_USER: root
      SPRING_DB_PASSWORD: 123
      SPRING_DB_URL: jdbc:postgresql://database:5432/db
    ports:
      - "8080:8080"